### ISSUE TITLE
licenses inconsistency

### ISSUE THREAD

**Issue by SoftwareEthicsResearcher** [upgundecha/howtheysre#101]
Hello, I am doing research in software engineering ethics. I found different licenses in repo. May I know which license repo follows? I would like to highlight this as a transparency concern.
•  Repo License: Creative Commons Zero v1.0 Universal, 
o  Different license : ISC in package.json.
 
Regards, Software Ethics Researcher.

**Comment by upgundecha** [comment]
Fixed in https://github.com/upgundecha/howtheysre/commit/a49608f70d36ea2df9ef02ef9ea1b31476351619
